# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Adopte un Make
email: eric@regit.org
description: > # this means to ignore newlines until "baseurl:"
  Adopte un make. Une initiative de conservation logicielle.
  Présenter des logiciels orphelins à des développeurs et mainteneurs potentiels
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.adopteunemake.com" # the base hostname & protocol for your site
twitter_username: regiteric
github_username:  regit

# Build settings
markdown: kramdown
